spring:
  application:
    name: backend
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    enabled: false
